"""Create impfpass and impfrequirements tables

Revision ID: 5d6aca7434f7
Revises: e732bfffbedf
Create Date: 2025-05-18 10:44:49.094768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6aca7434f7'
down_revision = 'e732bfffbedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impfrequirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('land', sa.String(length=100), nullable=False),
    sa.Column('impfstoff', sa.String(length=100), nullable=False),
    sa.Column('gueltigkeitsdauer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impfpass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('impfstoff', sa.String(length=100), nullable=False),
    sa.Column('hersteller', sa.String(length=100), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fk_impfass_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_impfass_id', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('impfpass')
    op.drop_table('impfrequirements')
    # ### end Alembic commands ###
