"""Add MFA fields to User model

Revision ID: b50a6dead741
Revises: 5d6aca7434f7
Create Date: 2026-01-12 21:46:07.488414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50a6dead741'
down_revision = '5d6aca7434f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('mfa_secret', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_secret')
        batch_op.drop_column('mfa_enabled')

    # ### end Alembic commands ###
