"""empty message

Revision ID: e732bfffbedf
Revises: 
Create Date: 2025-05-11 17:48:17.807761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e732bfffbedf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('vaccinations')
    op.drop_table('country_requirements')
    op.drop_table('recommendations')
    op.drop_table('countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('countries_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='countries_pkey'),
    sa.UniqueConstraint('name', name='countries_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='recommendations_country_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='recommendations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recommendations_pkey')
    )
    op.create_table('country_requirements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vaccine_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('required', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='country_requirements_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='country_requirements_pkey')
    )
    op.create_table('vaccinations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_given', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('valid_until', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='vaccinations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vaccinations_pkey')
    )
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('upload_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='documents_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='documents_pkey')
    )
    # ### end Alembic commands ###
